{
    "name": """No tickets without Email""",
    "summary": """User registration at your portal is always a plus for marketing""",
    "category": "Marketing",
    "images": ["images/banner.jpg"],
    "version": "14.0.1.0.0",
    "application": False,
    "author": "IT-Projects LLC",
    "support": "apps@it-projects.info",
    "website": "https://github.com/it-projects-llc/website-addons",
    "license": "LGPL-3",
    "depends": ["website_event"],
    "data": ["views/website_event_sale_templates.xml"],
    "qweb": [],
    "demo": [],
}
